### ISSUE TITLE
your indexed records for http://www.cfsph.iastate.edu/Factsheets/pdfs/menangle..pdf

### ISSUE THREAD

**Issue by jhpoelen** [arw36/willoughby-etal-2017-virus-interactions#4]
Hi!

Thanks for helping to make existing biotic interaction data easier to find and access!

I was just looking at your GloBI indexed record at https://www.globalbioticinteractions.org/?accordingTo=globi%3Aarw36%2Fwilloughby-etal-2017-virus-interactions&interactionType=ecologicallyRelatedTo and I was wondering about the citation:

```http://www.cfsph.iastate.edu/Factsheets/pdfs/menangle..pdf```

I suspect that an extra period ```.``` was added by accident, because the link: 
```http://www.cfsph.iastate.edu/Factsheets/pdfs/menangle.pdf```

resolves ok.

**Comment by arw36** [comment]
Fixed. looks like remnant typo copied from Olival et al. 2017.

**Comment by jhpoelen** [comment]
Thanks!
